//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SPOCPI.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shell.SPOCPI.Common.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activityLimitReached.
        /// </summary>
        public static string ActivityLimitError {
            get {
                return ResourceManager.GetString("ActivityLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No RowKey available.
        /// </summary>
        public static string AddDriveDeltaEntityNoRowKey {
            get {
                return ResourceManager.GetString("AddDriveDeltaEntityNoRowKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bearer.
        /// </summary>
        public static string AuthorizationTokenType {
            get {
                return ResourceManager.GetString("AuthorizationTokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated.
        /// </summary>
        public static string ChangeTypeUpdated {
            get {
                return ResourceManager.GetString("ChangeTypeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client cannot be null.
        /// </summary>
        public static string ClientNotNull {
            get {
                return ResourceManager.GetString("ClientNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table cannot be null.
        /// </summary>
        public static string CloudTableNotNull {
            get {
                return ResourceManager.GetString("CloudTableNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfidentialSite.
        /// </summary>
        public static string ConfidentialSite {
            get {
                return ResourceManager.GetString("ConfidentialSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site is confidential. access to this is restricted.
        /// </summary>
        public static string ConfidentialSiteError {
            get {
                return ResourceManager.GetString("ConfidentialSiteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site is confidential. subscription to this is restricted.
        /// </summary>
        public static string ConfidentialSubscriptionError {
            get {
                return ResourceManager.GetString("ConfidentialSubscriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AADAppClientId.
        /// </summary>
        public static string ConfigAADAppClientId {
            get {
                return ResourceManager.GetString("ConfigAADAppClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AADAppClientSecret.
        /// </summary>
        public static string ConfigAADAppClientSecret {
            get {
                return ResourceManager.GetString("ConfigAADAppClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppInsightsInstrumentationKey.
        /// </summary>
        public static string ConfigAppInsightsInstrumentationKey {
            get {
                return ResourceManager.GetString("ConfigAppInsightsInstrumentationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPDeltaTokenExpiryDays.
        /// </summary>
        public static string ConfigCPDeltaTokenExpiryDays {
            get {
                return ResourceManager.GetString("ConfigCPDeltaTokenExpiryDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPDriveDeltaStoreConnString.
        /// </summary>
        public static string ConfigCPDriveDeltaStoreConnString {
            get {
                return ResourceManager.GetString("ConfigCPDriveDeltaStoreConnString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPDriveDeltaTableName.
        /// </summary>
        public static string ConfigCPDriveDeltaTableName {
            get {
                return ResourceManager.GetString("ConfigCPDriveDeltaTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPDriveDeltaTransTableName.
        /// </summary>
        public static string ConfigCPDriveDeltaTransTableName {
            get {
                return ResourceManager.GetString("ConfigCPDriveDeltaTransTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPInputQueueName.
        /// </summary>
        public static string ConfigCPInputQueueName {
            get {
                return ResourceManager.GetString("ConfigCPInputQueueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPMaxRetryAttempts.
        /// </summary>
        public static string ConfigCPMaxRetryAttempts {
            get {
                return ResourceManager.GetString("ConfigCPMaxRetryAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPNotificationFetchCount.
        /// </summary>
        public static string ConfigCPNotificationFetchCount {
            get {
                return ResourceManager.GetString("ConfigCPNotificationFetchCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPOutputQueueName.
        /// </summary>
        public static string ConfigCPOutputQueueName {
            get {
                return ResourceManager.GetString("ConfigCPOutputQueueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPQueryFields.
        /// </summary>
        public static string ConfigCPQueryFields {
            get {
                return ResourceManager.GetString("ConfigCPQueryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPServiceBusConnectionString.
        /// </summary>
        public static string ConfigCPServiceBusConnectionString {
            get {
                return ResourceManager.GetString("ConfigCPServiceBusConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataContainerName.
        /// </summary>
        public static string ConfigDataContainerName {
            get {
                return ResourceManager.GetString("ConfigDataContainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentTrackingTableName.
        /// </summary>
        public static string ConfigDocumentTrackingTableName {
            get {
                return ResourceManager.GetString("ConfigDocumentTrackingTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTMLInputValidation.
        /// </summary>
        public static string ConfigHTMLInputValidation {
            get {
                return ResourceManager.GetString("ConfigHTMLInputValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsLoggingEnabled.
        /// </summary>
        public static string ConfigIsLoggingEnabled {
            get {
                return ResourceManager.GetString("ConfigIsLoggingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputQueueNames.
        /// </summary>
        public static string ConfigOutputQueueNames {
            get {
                return ResourceManager.GetString("ConfigOutputQueueNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchServiceName.
        /// </summary>
        public static string ConfigSearchServiceName {
            get {
                return ResourceManager.GetString("ConfigSearchServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchUpdateKey.
        /// </summary>
        public static string ConfigSearchUpdateKey {
            get {
                return ResourceManager.GetString("ConfigSearchUpdateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubscriptionExpirationDays.
        /// </summary>
        public static string ConfigSubscriptionExpirationDays {
            get {
                return ResourceManager.GetString("ConfigSubscriptionExpirationDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubscriptionIndexerName.
        /// </summary>
        public static string ConfigSubscriptionIndexerName {
            get {
                return ResourceManager.GetString("ConfigSubscriptionIndexerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubscriptionIndexName.
        /// </summary>
        public static string ConfigSubscriptionIndexName {
            get {
                return ResourceManager.GetString("ConfigSubscriptionIndexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TenantId.
        /// </summary>
        public static string ConfigTenantId {
            get {
                return ResourceManager.GetString("ConfigTenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TenantName.
        /// </summary>
        public static string ConfigTenantName {
            get {
                return ResourceManager.GetString("ConfigTenantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrackingIndexerName.
        /// </summary>
        public static string ConfigTrackingIndexerName {
            get {
                return ResourceManager.GetString("ConfigTrackingIndexerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrackingIndexName.
        /// </summary>
        public static string ConfigTrackingIndexName {
            get {
                return ResourceManager.GetString("ConfigTrackingIndexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebhookNotificationUrl.
        /// </summary>
        public static string ConfigWebhookNotificationUrl {
            get {
                return ResourceManager.GetString("ConfigWebhookNotificationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebHooksStoreConnectionString.
        /// </summary>
        public static string ConfigWebHooksStoreConnectionString {
            get {
                return ResourceManager.GetString("ConfigWebHooksStoreConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Executing Action: {0}.
        /// </summary>
        public static string ContextAction {
            get {
                return ResourceManager.GetString("ContextAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Endpoint: {0}.
        /// </summary>
        public static string ContextEndpoint {
            get {
                return ResourceManager.GetString("ContextEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Entity Path: {0}.
        /// </summary>
        public static string ContextEntityPath {
            get {
                return ResourceManager.GetString("ContextEntityPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00:30:00.
        /// </summary>
        public static string CustomTimerValue {
            get {
                return ResourceManager.GetString("CustomTimerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @odata.deltaLink.
        /// </summary>
        public static string DataDeltaLink {
            get {
                return ResourceManager.GetString("DataDeltaLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @odata.nextLink.
        /// </summary>
        public static string DataNextLink {
            get {
                return ResourceManager.GetString("DataNextLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred in DeleteDocumentTrackingData : {0}.
        /// </summary>
        public static string DeleteDocumetErrorMessage {
            get {
                return ResourceManager.GetString("DeleteDocumetErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete documents: {0}.
        /// </summary>
        public static string DeletionFailed {
            get {
                return ResourceManager.GetString("DeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta token query results count: {0}.
        /// </summary>
        public static string DeltaTokenResultsCount {
            get {
                return ResourceManager.GetString("DeltaTokenResultsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception context for troubleshooting: {0}.
        /// </summary>
        public static string ExceptionContext {
            get {
                return ResourceManager.GetString("ExceptionContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HostName cannot be null.
        /// </summary>
        public static string HostNotNull {
            get {
                return ResourceManager.GetString("HostNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Connection String.
        /// </summary>
        public static string InvalidConnection {
            get {
                return ResourceManager.GetString("InvalidConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Subscription Expiration Days cannot be more than 21 days..
        /// </summary>
        public static string InvalidSubscriptionExpirationDaysValue {
            get {
                return ResourceManager.GetString("InvalidSubscriptionExpirationDaysValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Input.
        /// </summary>
        public static string InvalidUserInput {
            get {
                return ResourceManager.GetString("InvalidUserInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested table item was not found, please wait for the azure index to update, aprox 5 mins.
        /// </summary>
        public static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The library doesn&apos;t exists in the Site provided..
        /// </summary>
        public static string LibraryDoesNotExist {
            get {
                return ResourceManager.GetString("LibraryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LibraryUrl.
        /// </summary>
        public static string LibraryUrl {
            get {
                return ResourceManager.GetString("LibraryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message for the Library Url : {0}.
        /// </summary>
        public static string LibraryUrlError {
            get {
                return ResourceManager.GetString("LibraryUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message has exceeded maximum size of {0} per message. Please try with lesser number of messageMaxItems..
        /// </summary>
        public static string MessageSizeExceeded {
            get {
                return ResourceManager.GetString("MessageSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type is not serializable.
        /// </summary>
        public static string NotSerializable {
            get {
                return ResourceManager.GetString("NotSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} not found.
        /// </summary>
        public static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type is not serializable.
        /// </summary>
        public static string QHTypeNotSerializable {
            get {
                return ResourceManager.GetString("QHTypeNotSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token.
        /// </summary>
        public static string QueryOptionTokenKey {
            get {
                return ResourceManager.GetString("QueryOptionTokenKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latest.
        /// </summary>
        public static string QueryOptionTokenLatestValue {
            get {
                return ResourceManager.GetString("QueryOptionTokenLatestValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quotaLimitReached.
        /// </summary>
        public static string QuotaLimitError {
            get {
                return ResourceManager.GetString("QuotaLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string RequestHeaderAuthorization {
            get {
                return ResourceManager.GetString("RequestHeaderAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearer .
        /// </summary>
        public static string RequestHeaderAuthorizationType {
            get {
                return ResourceManager.GetString("RequestHeaderAuthorizationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resyncRequired.
        /// </summary>
        public static string ResyncRequiredError {
            get {
                return ResourceManager.GetString("ResyncRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serviceNotAvailable.
        /// </summary>
        public static string ServiceNotAvailableError {
            get {
                return ResourceManager.GetString("ServiceNotAvailableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiteId cannot be null.
        /// </summary>
        public static string SiteIdNotNull {
            get {
                return ResourceManager.GetString("SiteIdNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiteRelativeUrl cannot be null.
        /// </summary>
        public static string SiteRelativeUrlNotNull {
            get {
                return ResourceManager.GetString("SiteRelativeUrlNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Id : {0} is deleted for the Library Url : {1}.
        /// </summary>
        public static string SubscriptionDeleted {
            get {
                return ResourceManager.GetString("SubscriptionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription : {0} is updated with ExpirationDate set to : {1}.
        /// </summary>
        public static string SubscriptionExpirationDateUpdated {
            get {
                return ResourceManager.GetString("SubscriptionExpirationDateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubscriptionId cannot be null.
        /// </summary>
        public static string SubscriptionIdNotNull {
            get {
                return ResourceManager.GetString("SubscriptionIdNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Id {0} &amp; Status : {1} are updated for the library Url : {2}.
        /// </summary>
        public static string SubscriptionIdStatusUpdated {
            get {
                return ResourceManager.GetString("SubscriptionIdStatusUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Info - ChangeType: {0} &amp; ClientState: {1} &amp; ExpirationDateTime: {2} &amp; NotificationUrl: {3} &amp; Resource: {4}.
        /// </summary>
        public static string SubscriptionInfo {
            get {
                return ResourceManager.GetString("SubscriptionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription cannot be null.
        /// </summary>
        public static string SubscriptionNotNull {
            get {
                return ResourceManager.GetString("SubscriptionNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Id {0} &amp; ExpirationDate: {1} will be processed for renewal.
        /// </summary>
        public static string SubscriptionObjectToBeRenewed {
            get {
                return ResourceManager.GetString("SubscriptionObjectToBeRenewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription status is updated to Not Subscribed during Renewal for library : {1}.
        /// </summary>
        public static string SubscriptionStatusUpdateByRenew {
            get {
                return ResourceManager.GetString("SubscriptionStatusUpdateByRenew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription status is updated to Not Subscribed during Resource not found exception for library : {1}.
        /// </summary>
        public static string SubscriptionStatusUpdateByResourceNotFound {
            get {
                return ResourceManager.GetString("SubscriptionStatusUpdateByResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Id: {0} &amp; Status : {1} will be processed for subscription creation for the library Url : {2}.
        /// </summary>
        public static string SubscriptionToBeCreated {
            get {
                return ResourceManager.GetString("SubscriptionToBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Id: {0} &amp; Status : {1} will be processed for renewal for the library Url : {2}.
        /// </summary>
        public static string SubscriptionToBeRenewed {
            get {
                return ResourceManager.GetString("SubscriptionToBeRenewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Table Entry is deleted for the item with RowKey : {0}.
        /// </summary>
        public static string TableEntryDeleted {
            get {
                return ResourceManager.GetString("TableEntryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token=&apos;.
        /// </summary>
        public static string Token1 {
            get {
                return ResourceManager.GetString("Token1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token=.
        /// </summary>
        public static string Token2 {
            get {
                return ResourceManager.GetString("Token2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;).
        /// </summary>
        public static string Token3 {
            get {
                return ResourceManager.GetString("Token3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict error thrown while trying to update drive delta entity.
        /// </summary>
        public static string UpdateDriveDeltaStatusConflict {
            get {
                return ResourceManager.GetString("UpdateDriveDeltaStatusConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while trying to update drive delta entity.
        /// </summary>
        public static string UpdateDriveDeltaStatusError {
            get {
                return ResourceManager.GetString("UpdateDriveDeltaStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url cannot be empty or null.
        /// </summary>
        public static string UrlNotNull {
            get {
                return ResourceManager.GetString("UrlNotNull", resourceCulture);
            }
        }
    }
}
