//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SPOCPI.ChangeProcessor.WebJob {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shell.SPOCPI.ChangeProcessor.WebJob.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No RowKey available.
        /// </summary>
        public static string AddDriveDeltaEntityNoRowKey {
            get {
                return ResourceManager.GetString("AddDriveDeltaEntityNoRowKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Item to drive item list: .
        /// </summary>
        public static string AddedDriveItem {
            get {
                return ResourceManager.GetString("AddedDriveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPCustomMinuteSchedule.
        /// </summary>
        public static string ChangeProcessorCustomMinuteSchedule {
            get {
                return ResourceManager.GetString("ChangeProcessorCustomMinuteSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating notification status in Notification storage table..
        /// </summary>
        public static string CompleteMessageProcessingNotificationError {
            get {
                return ResourceManager.GetString("CompleteMessageProcessingNotificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully completed updating notification status in Notification storage table..
        /// </summary>
        public static string CompleteMessageProcessingNotificationSuccess {
            get {
                return ResourceManager.GetString("CompleteMessageProcessingNotificationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating deltaToken in Drive delta storage table..
        /// </summary>
        public static string CompleteMessageProcessingTokenError {
            get {
                return ResourceManager.GetString("CompleteMessageProcessingTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully completed updating deltaToken in Drive delta storage table..
        /// </summary>
        public static string CompleteMessageProcessingTokenSuccess {
            get {
                return ResourceManager.GetString("CompleteMessageProcessingTokenSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta Found {0} changes..
        /// </summary>
        public static string DeltaNumberOfChange {
            get {
                return ResourceManager.GetString("DeltaNumberOfChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta token query results count: {0}.
        /// </summary>
        public static string DeltaTokenResultsCount {
            get {
                return ResourceManager.GetString("DeltaTokenResultsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Drive Items: {0}.
        /// </summary>
        public static string DriveItemCount {
            get {
                return ResourceManager.GetString("DriveItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed pushing Drive Items to queue: {0}.
        /// </summary>
        public static string DriveItemsQueueCompleted {
            get {
                return ResourceManager.GetString("DriveItemsQueueCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Drive Items sent to queue: {0}.
        /// </summary>
        public static string DriveItemsQueueCount {
            get {
                return ResourceManager.GetString("DriveItemsQueueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorHandler called. Function {0}:{1} failed..
        /// </summary>
        public static string ErrorHandlerMessage {
            get {
                return ResourceManager.GetString("ErrorHandlerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized Function successfully.
        /// </summary>
        public static string FunctionsInitializationSuccess {
            get {
                return ResourceManager.GetString("FunctionsInitializationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find NotificationMessage storage table..
        /// </summary>
        public static string GetMessageFromStorageNoNotification {
            get {
                return ResourceManager.GetString("GetMessageFromStorageNoNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not targeted for document processing.
        /// </summary>
        public static string ItemNotTargeted {
            get {
                return ResourceManager.GetString("ItemNotTargeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errow when trying to acquire lock on notification of same batch for processing..
        /// </summary>
        public static string LockForProcessingBatchNotificationError {
            get {
                return ResourceManager.GetString("LockForProcessingBatchNotificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to acquire lock on notification of same batch for processing..
        /// </summary>
        public static string LockForProcessingBatchNotificationFailed {
            get {
                return ResourceManager.GetString("LockForProcessingBatchNotificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired lock partial on notification of same batch for processing..
        /// </summary>
        public static string LockForProcessingBatchNotificationPartialSuccess {
            get {
                return ResourceManager.GetString("LockForProcessingBatchNotificationPartialSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired lock on notification of same batch for processing..
        /// </summary>
        public static string LockForProcessingBatchNotificationSuccess {
            get {
                return ResourceManager.GetString("LockForProcessingBatchNotificationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to acquire lock on notification for processing. Rolling back the changes..
        /// </summary>
        public static string LockForProcessingDeltaFailed {
            get {
                return ResourceManager.GetString("LockForProcessingDeltaFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to release lock on drive delta for processing..
        /// </summary>
        public static string LockForProcessingDeltaReleaseSuccess {
            get {
                return ResourceManager.GetString("LockForProcessingDeltaReleaseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully acquired lock on drive delta for processing..
        /// </summary>
        public static string LockForProcessingDeltaSuccess {
            get {
                return ResourceManager.GetString("LockForProcessingDeltaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to acquire lock on notifications.
        /// </summary>
        public static string LockForProcessingNotificationError {
            get {
                return ResourceManager.GetString("LockForProcessingNotificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to acquire lock on notification for processing..
        /// </summary>
        public static string LockForProcessingNotificationFailed {
            get {
                return ResourceManager.GetString("LockForProcessingNotificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully acquired lock on notification for processing..
        /// </summary>
        public static string LockForProcessingNotificationSuccess {
            get {
                return ResourceManager.GetString("LockForProcessingNotificationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum retry attempts {0}, has been attempted..
        /// </summary>
        public static string MaximumRetryAttemptWarning {
            get {
                return ResourceManager.GetString("MaximumRetryAttemptWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} messages for processing..
        /// </summary>
        public static string MessagesCount {
            get {
                return ResourceManager.GetString("MessagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Received for subscription: {0}.
        /// </summary>
        public static string NotificationReceived {
            get {
                return ResourceManager.GetString("NotificationReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessQueue Completed at:.
        /// </summary>
        public static string ProcessQueueCompleted {
            get {
                return ResourceManager.GetString("ProcessQueueCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessQueue Triggered at:.
        /// </summary>
        public static string ProcessQueueTrigerred {
            get {
                return ResourceManager.GetString("ProcessQueueTrigerred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Delta token has been set to the variable..
        /// </summary>
        public static string ProcessSharePointChangesDeltaTokenSet {
            get {
                return ResourceManager.GetString("ProcessSharePointChangesDeltaTokenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing SharePoint changes completed.
        /// </summary>
        public static string ProcessSharePointChangesSPCompleted {
            get {
                return ResourceManager.GetString("ProcessSharePointChangesSPCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errow when trying to unlock notification of same batch for processing..
        /// </summary>
        public static string UnlockForProcessingBatchNotificationError {
            get {
                return ResourceManager.GetString("UnlockForProcessingBatchNotificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to unlock notification of same batch for processing..
        /// </summary>
        public static string UnlockForProcessingBatchNotificationFailed {
            get {
                return ResourceManager.GetString("UnlockForProcessingBatchNotificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked partial on notification of same batch for processing..
        /// </summary>
        public static string UnlockForProcessingBatchNotificationPartialSuccess {
            get {
                return ResourceManager.GetString("UnlockForProcessingBatchNotificationPartialSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked notification of same batch for processing..
        /// </summary>
        public static string UnlockForProcessingBatchNotificationSuccess {
            get {
                return ResourceManager.GetString("UnlockForProcessingBatchNotificationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No DeltaUrl available.
        /// </summary>
        public static string UpdateDeltaTokenNoDeltaUrl {
            get {
                return ResourceManager.GetString("UpdateDeltaTokenNoDeltaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started updating deltaToken in Drive delta storage table..
        /// </summary>
        public static string UpdateDeltaTokenStart {
            get {
                return ResourceManager.GetString("UpdateDeltaTokenStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict error thrown while trying to update drive delta entity.
        /// </summary>
        public static string UpdateDriveDeltaStatusConflict {
            get {
                return ResourceManager.GetString("UpdateDriveDeltaStatusConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while trying to update drive delta entity.
        /// </summary>
        public static string UpdateDriveDeltaStatusError {
            get {
                return ResourceManager.GetString("UpdateDriveDeltaStatusError", resourceCulture);
            }
        }
    }
}
