//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SPOCPI.PopulateTracking.FunctionApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shell.SPOCPI.PopulateTracking.FunctionApp.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builder cannot be null.
        /// </summary>
        internal static string BuilderNull {
            get {
                return ResourceManager.GetString("BuilderNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received {0} items from changeprocessoutputqueue.
        /// </summary>
        internal static string CPItemsReceived {
            get {
                return ResourceManager.GetString("CPItemsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changeprocessoutputqueue.
        /// </summary>
        internal static string CPQueueName {
            get {
                return ResourceManager.GetString("CPQueueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received DriveItem cTag {0} Previous cTag {1}.
        /// </summary>
        internal static string CTagReceived {
            get {
                return ResourceManager.GetString("CTagReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added drive item with id: {0} to document tracking table.
        /// </summary>
        internal static string DriveItemAdded {
            get {
                return ResourceManager.GetString("DriveItemAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in adding drive item with id: {0} to document tracking table.
        /// </summary>
        internal static string DriveItemAddingFailed {
            get {
                return ResourceManager.GetString("DriveItemAddingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted drive item with id: {0} from document tracking table.
        /// </summary>
        internal static string DriveItemDeleted {
            get {
                return ResourceManager.GetString("DriveItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete drive item with id: {0} from document tracking table.
        /// </summary>
        internal static string DriveItemDeletingFailed {
            get {
                return ResourceManager.GetString("DriveItemDeletingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added drive items to queue: {0}, driveId: {1}.
        /// </summary>
        internal static string DriveItemsAddedToOutputQueue {
            get {
                return ResourceManager.GetString("DriveItemsAddedToOutputQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped drive item with id: {0} from adding to document tracking table as it is a System Update/Resync.
        /// </summary>
        internal static string DriveItemSkipped {
            get {
                return ResourceManager.GetString("DriveItemSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while adding drive items to output queue: {0}, drive id: {1}.
        /// </summary>
        internal static string ErrorAddingToOutputQueue {
            get {
                return ResourceManager.GetString("ErrorAddingToOutputQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received DriveItem eTag {0} Previous eTag {1}.
        /// </summary>
        internal static string ETagReceived {
            get {
                return ResourceManager.GetString("ETagReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in PopulateTracking FunctionApp..
        /// </summary>
        internal static string GeneralException {
            get {
                return ResourceManager.GetString("GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subscription found with the drive id: {0}.
        /// </summary>
        internal static string NoSubscriptionFound {
            get {
                return ResourceManager.GetString("NoSubscriptionFound", resourceCulture);
            }
        }
    }
}
