//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SPOCPI.MigrationPipeline.WebJob {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shell.SPOCPI.MigrationPipeline.WebJob.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered {0} function..
        /// </summary>
        internal static string EnterMethod {
            get {
                return ResourceManager.GetString("EnterMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        internal static string EqualsOperator {
            get {
                return ResourceManager.GetString("EqualsOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving {0} function..
        /// </summary>
        internal static string ExitMethod {
            get {
                return ResourceManager.GetString("ExitMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in {0} WebJob..
        /// </summary>
        internal static string GeneralException {
            get {
                return ResourceManager.GetString("GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in Migration Web Job. {0}..
        /// </summary>
        internal static string MigrationJobException {
            get {
                return ResourceManager.GetString("MigrationJobException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MigrationMinuteSchedule.
        /// </summary>
        internal static string MigrationMinuteSchedule {
            get {
                return ResourceManager.GetString("MigrationMinuteSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items to process from migration tracker table. .
        /// </summary>
        internal static string NoItemsToProcess {
            get {
                return ResourceManager.GetString("NoItemsToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Migration Pipelines Queued is {0}.
        /// </summary>
        internal static string NumberOfMigrationPipelinesQueued {
            get {
                return ResourceManager.GetString("NumberOfMigrationPipelinesQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PipelineName.
        /// </summary>
        internal static string PipelineName {
            get {
                return ResourceManager.GetString("PipelineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many Queued Pipelines. Skipping Proceesing..
        /// </summary>
        internal static string PipelineQueued {
            get {
                return ResourceManager.GetString("PipelineQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PipelineQueuedGap.
        /// </summary>
        internal static string PipelineQueuedGap {
            get {
                return ResourceManager.GetString("PipelineQueuedGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        internal static string Queued {
            get {
                return ResourceManager.GetString("Queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
    }
}
