//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell.SPOCPI.WebHooksManager.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shell.SPOCPI.WebHooksManager.UI.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No RowKey available.
        /// </summary>
        public static string AddDriveDeltaEntityNoRowKey {
            get {
                return ResourceManager.GetString("AddDriveDeltaEntityNoRowKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contact page..
        /// </summary>
        public static string ApplicationContact {
            get {
                return ResourceManager.GetString("ApplicationContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application description page..
        /// </summary>
        public static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AzureAd.
        /// </summary>
        public static string AzureAdInstance {
            get {
                return ResourceManager.GetString("AzureAdInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request: System cannot process more than 1000 items at a time..
        /// </summary>
        public static string BulkUploadProcessingMessage {
            get {
                return ResourceManager.GetString("BulkUploadProcessingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta token query results count: {0}.
        /// </summary>
        public static string DeltaTokenResultsCount {
            get {
                return ResourceManager.GetString("DeltaTokenResultsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveId.
        /// </summary>
        public static string DriveId {
            get {
                return ResourceManager.GetString("DriveId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Error.
        /// </summary>
        public static string ErrorPage {
            get {
                return ResourceManager.GetString("ErrorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something bad happened for the Subscription ID : {0}. Please try after some time..
        /// </summary>
        public static string NoDriveDeltaEntryFound {
            get {
                return ResourceManager.GetString("NoDriveDeltaEntryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting and recreating the key. please try again.
        /// </summary>
        public static string RedisErrorMessage {
            get {
                return ResourceManager.GetString("RedisErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the valid key.
        /// </summary>
        public static string RedisInvalidKey {
            get {
                return ResourceManager.GetString("RedisInvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key doesnot exist.
        /// </summary>
        public static string RedisKeyNotExsits {
            get {
                return ResourceManager.GetString("RedisKeyNotExsits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted and recreated redis key successfully.
        /// </summary>
        public static string RedisSuccessMessage {
            get {
                return ResourceManager.GetString("RedisSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        public static string RouteName {
            get {
                return ResourceManager.GetString("RouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {controller=Home}/{action=Index}/{id?}.
        /// </summary>
        public static string RouteTemplate {
            get {
                return ResourceManager.GetString("RouteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to driveId.
        /// </summary>
        public static string SmallDriveId {
            get {
                return ResourceManager.GetString("SmallDriveId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription-{0}.
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A subscription is already present with the same library url..
        /// </summary>
        public static string SubscriptionAlreadyPresent {
            get {
                return ResourceManager.GetString("SubscriptionAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription entity is null.
        /// </summary>
        public static string SubscriptionEntityNull {
            get {
                return ResourceManager.GetString("SubscriptionEntityNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription is already marked .
        /// </summary>
        public static string SubscriptionMarked {
            get {
                return ResourceManager.GetString("SubscriptionMarked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription is already marked Delete.
        /// </summary>
        public static string SubscritionMarkedDeletion {
            get {
                return ResourceManager.GetString("SubscritionMarkedDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict error thrown while trying to update drive delta entity.
        /// </summary>
        public static string UpdateDriveDeltaStatusConflict {
            get {
                return ResourceManager.GetString("UpdateDriveDeltaStatusConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while trying to update drive delta entity.
        /// </summary>
        public static string UpdateDriveDeltaStatusError {
            get {
                return ResourceManager.GetString("UpdateDriveDeltaStatusError", resourceCulture);
            }
        }
    }
}
