variables:
  - name: "ServicesOrg"
    value: 'Shell-MicrosoftSearchAndKnowledge'
  - name: "OrganizationUri"
    value: '$(System.TeamFoundationCollectionUri)'
  - name: "SolutionName"
    value: "Shell.SPOCPI"
  - name: "BuildPlatform"
    value: "Any CPU"
  - name: "BuildConfiguration"
    value: "Release"
  - name : "ScanPSScripts"
    value: true
  - name : "DeploymentScriptsRoot"
    value: "$(Build.SourcesDirectory)/deploy"
  - name : "npm_config_cache"
    value: $(Pipeline.Workspace)/.npm  

  # SonarQube Region
  - name: "ExecuteServicesSonar"
    value: false
  - name: "SonarQube"
    value: "ServicesCODE-PROD"
  - name: "projectKey"
    value: "IPDitalWorkplace_LEDdev"
  - name: "projectName"
    value: "IPDitalWorkplace_IPKitSharePoint_LEDdev_#MW"
  # SonarQube Region

  - name: "SelfHostedPool"
    value: true

  - name: "TeamsDevelopmentMode"
    value: false